import './offer.js';
console.log('offer!');
import './page-load.js';
console.log('load!');
import './map.js';
console.log('map!');
import './form.js';
console.log('form!');
import './fetch.js';
console.log('fetch!');
import './notice.js';
